version: "3"
services:
  doimoisangtao-strapi:
    container_name: doimoisangtao-strapi
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: doimoisangtao-strapi:latest
    restart: unless-stopped
    env_file: .env.prod
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - doimoisangtao-network
volumes:
  doimoisangtao-strapi-data:

networks:
  doimoisangtao-network:
    external: true
